version: "3.8"
services:
  hapi-fhir-jpaserver-start:
    build: .
    container_name: hapi-fhir-jpaserver-start
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./src:/tmp/hapi-fhir-jpaserver-starter/src/
  hapi-fhir-postgres:
    image: postgres
    container_name: hapi-fhir-postgres
    restart: always
    environment:
      POSTGRES_DB: "hapi"
      POSTGRES_USER: "hapi"
      POSTGRES_PASSWORD: "hapi"
    ports:
      - 5432:5432
    volumes:
      - hapi-fhir-postgresData:/var/lib/postgresql/data
  hap-fhir-pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root254
    ports:
      - "5050:80"
volumes:
  hapi-fhir-postgresData:
